window.HP_LANGS = {
    en: {
        'status.running': 'running',
        'status.stopped': 'stopped',
        'header.restart': 'Restart',
        'tab.subscriptions': 'VPNs',
        'tab.rulesets': 'Domains',

        'subs.title': 'VPNs',
        'subs.refresh': 'Refresh All',
        'subs.add': '+ Add',
        'subs.hint': 'Add your VPN provider links, then "Refresh All" to download servers.',
        'subs.empty': 'No VPNs yet. Click "+ Add" to add your VPN provider link.',
        'subs.loading': 'Loading...',
        'subs.noServers': 'No servers. Click "Refresh All" to download.',

        'warning.routingMode': 'Routing mode is not set to "custom". Rule routing only works in custom mode.',

        'nodes.title': 'Custom Servers',
        'nodes.add': '+ Add Server',
        'nodes.hint': 'Manually add VPN servers (WireGuard, etc.).',
        'nodes.empty': 'No custom servers.',

        'custom.title': 'Custom Rules',
        'custom.add': '+ Add',
        'custom.hint': 'Add domains or IP ranges that should be routed through VPN.',
        'custom.empty': 'No custom rules yet. Click "+ Add" to add a domain or IP CIDR.',

        'rulesets.title': 'Rule Sets',
        'rulesets.add': '+ Add',
        'rulesets.hint': 'External rule set files that define which traffic gets routed through VPN. Add links to <code>.srs</code> files.',
        'rulesets.empty': 'No rule sets. Click "+ Add" to add a rule set URL.',

        'chip.refreshHint': 'Refresh VPN to enable routing',
        'chip.addRuleset': '+ Add Rule Set',
        'chip.allConnected': 'All rule sets are already connected',

        'modal.cancel': 'Cancel',
        'modal.save': 'Save',
        'modal.or': 'or',
        'modal.manualEntry': 'Fill in manually',
        'modal.addSub': 'Add VPN',
        'modal.connectRuleset': 'Connect Rule Set',
        'modal.addServer': 'Add Custom Server',
        'modal.addRuleset': 'Add Rule Set',
        'modal.addCustomRule': 'Add Custom Rule',

        'field.name': 'Display Name',
        'field.url': 'URL',
        'field.selectRuleset': 'Select Rule Set',
        'field.type': 'Type',
        'field.serverName': 'Name',
        'field.serverAddr': 'Server Address',
        'field.serverPort': 'Server Port',
        'field.password': 'Password',
        'field.ssMethod': 'Encryption Method',
        'field.vmessEncrypt': 'Encryption',
        'field.vlessFlow': 'Flow',
        'field.transport': 'Transport',
        'field.wsHost': 'WebSocket Host',
        'field.wsPath': 'WebSocket Path',
        'field.grpcService': 'gRPC Service Name',
        'field.httpHost': 'HTTP Host',
        'field.httpPath': 'HTTP Path',
        'field.httpupgradeHost': 'HTTPUpgrade Host',
        'field.hyObfsPassword': 'Obfs Password',
        'field.privateKey': 'Private Key',
        'field.peerPublicKey': 'Peer Public Key',
        'field.localIpv4': 'Local IPv4',
        'field.localIpv6': 'Local IPv6',
        'field.dns': 'DNS',
        'field.allowedIps': 'Allowed IPs',
        'field.mtu': 'MTU',
        'field.reserved': 'Reserved',
        'field.preSharedKey': 'Pre-Shared Key',
        'field.rulesetName': 'Name',
        'field.rulesetUrl': 'Rule Set URL (.srs)',
        'field.ruleType': 'Type',
        'field.ruleValue': 'Value',

        'ph.name': 'My VPN',
        'ph.url': 'https://provider.com/subscribe/...',
        'ph.serverName': 'My WireGuard',
        'ph.serverAddr': '1.2.3.4 or domain',
        'ph.serverPort': '51820',
        'ph.uuid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'ph.password': 'password',
        'ph.tlsSni': 'example.com',
        'ph.wsHost': 'example.com',
        'ph.wsPath': '/path',
        'ph.grpcService': 'service_name',
        'ph.httpHost': 'example.com',
        'ph.httpPath': '/path',
        'ph.httpupgradeHost': 'example.com',
        'ph.hyObfsPassword': 'obfs password',
        'ph.privateKey': 'base64 key',
        'ph.peerPublicKey': 'base64 key',
        'ph.localIpv4': '10.0.0.2/32',
        'ph.localIpv6': 'fd00::2/128',
        'ph.dns': '1.1.1.1, 8.8.8.8',
        'ph.allowedIps': '0.0.0.0/0, ::/0',
        'ph.mtu': '1420',
        'ph.reserved': '0, 0, 0',
        'ph.preSharedKey': 'base64 key',
        'opt.none': 'None',
        'opt.disabled': 'Disabled',
        'opt.enabled': 'Enabled',
        'field.importUri': 'Import from URL',
        'ph.importUri': 'vless://... or vmess://... or ss://...',
        'ph.rulesetName': 'GeoIP-CN',
        'ph.rulesetUrl': 'https://.../.srs',
        'ph.domain': 'example.com',
        'ph.ipCidr': '10.0.0.0/8',

        'msg.invalidUri': 'Could not parse this URL',
        'msg.pasteUri': 'Paste a server URL or use manual entry',
        'msg.disconnected': 'Disconnected',
        'msg.connected': 'Connected',
        'msg.deleted': 'Deleted',
        'msg.subAdded': 'VPN added',
        'msg.subEnabled': 'VPN enabled',
        'msg.subDisabled': 'VPN disabled',
        'msg.subsUpdated': 'VPNs updated',
        'msg.updateFailed': 'Update failed',
        'msg.connFailed': 'Connection failed',
        'msg.nodeEnabled': 'Server enabled',
        'msg.nodeDisabled': 'Server disabled',
        'msg.serverAdded': 'Server added',
        'msg.rulesetAdded': 'Rule set added',
        'msg.ruleAdded': 'Rule added',
        'msg.restarted': 'HomeProxy restarted',
        'msg.urlRequired': 'URL is required',
        'msg.nameUrlRequired': 'Name and URL are required',
        'msg.nameAddrPortRequired': 'Name, address and port are required',
        'msg.valueRequired': 'Value is required',
        'msg.error': 'Error: ',

        'confirm.deleteSub': 'Delete VPN "{name}" and all its servers?',
        'confirm.deleteNode': 'Delete server "{name}"?',
        'confirm.deleteRuleset': 'Delete rule set "{name}"?',
        'confirm.deleteRule': 'Delete "{value}"?',
        'confirm.restart': 'Restart HomeProxy?',

        'btn.updating': 'Updating...',
        'btn.restarting': 'Restarting...'
    },
    ru: {
        'status.running': 'работает',
        'status.stopped': 'остановлен',
        'header.restart': 'Перезапуск',
        'tab.subscriptions': 'VPN',
        'tab.rulesets': 'Домены',

        'subs.title': 'VPN',
        'subs.refresh': 'Обновить все',
        'subs.add': '+ Добавить',
        'subs.hint': 'Добавьте ссылки VPN-провайдера, затем нажмите «Обновить все» для загрузки серверов.',
        'subs.empty': 'VPN ещё нет. Нажмите «+ Добавить», чтобы добавить ссылку провайдера.',
        'subs.loading': 'Загрузка...',
        'subs.noServers': 'Нет серверов. Нажмите «Обновить все» для загрузки.',

        'warning.routingMode': 'Режим маршрутизации не установлен в «custom». Правила работают только в режиме custom.',

        'nodes.title': 'Свои серверы',
        'nodes.add': '+ Добавить сервер',
        'nodes.hint': 'Добавляйте VPN-серверы вручную (WireGuard и др.).',
        'nodes.empty': 'Нет своих серверов.',

        'custom.title': 'Свои правила',
        'custom.add': '+ Добавить',
        'custom.hint': 'Добавьте домены или IP-диапазоны, которые должны идти через VPN.',
        'custom.empty': 'Своих правил пока нет. Нажмите «+ Добавить», чтобы добавить домен или IP CIDR.',

        'rulesets.title': 'Наборы правил',
        'rulesets.add': '+ Добавить',
        'rulesets.hint': 'Внешние файлы правил, определяющие какой трафик идёт через VPN. Добавьте ссылки на файлы <code>.srs</code>.',
        'rulesets.empty': 'Наборов правил нет. Нажмите «+ Добавить», чтобы добавить URL.',

        'chip.refreshHint': 'Обновите VPN для настройки маршрутизации',
        'chip.addRuleset': '+ Правило',
        'chip.allConnected': 'Все наборы правил уже подключены',

        'modal.cancel': 'Отмена',
        'modal.save': 'Сохранить',
        'modal.or': 'или',
        'modal.manualEntry': 'Заполнить вручную',
        'modal.addSub': 'Добавить VPN',
        'modal.connectRuleset': 'Подключить набор правил',
        'modal.addServer': 'Добавить сервер',
        'modal.addRuleset': 'Добавить набор правил',
        'modal.addCustomRule': 'Добавить правило',

        'field.name': 'Название',
        'field.url': 'URL',
        'field.selectRuleset': 'Выберите набор правил',
        'field.type': 'Тип',
        'field.serverName': 'Название',
        'field.serverAddr': 'Адрес сервера',
        'field.serverPort': 'Порт сервера',
        'field.password': 'Пароль',
        'field.ssMethod': 'Метод шифрования',
        'field.vmessEncrypt': 'Шифрование',
        'field.vlessFlow': 'Flow',
        'field.transport': 'Транспорт',
        'field.wsHost': 'WebSocket Host',
        'field.wsPath': 'WebSocket Path',
        'field.grpcService': 'gRPC Service Name',
        'field.httpHost': 'HTTP Host',
        'field.httpPath': 'HTTP Path',
        'field.httpupgradeHost': 'HTTPUpgrade Host',
        'field.hyObfsPassword': 'Пароль обфускации',
        'field.privateKey': 'Приватный ключ',
        'field.peerPublicKey': 'Публичный ключ пира',
        'field.localIpv4': 'Локальный IPv4',
        'field.localIpv6': 'Локальный IPv6',
        'field.dns': 'DNS',
        'field.allowedIps': 'Allowed IPs',
        'field.mtu': 'MTU',
        'field.reserved': 'Reserved',
        'field.preSharedKey': 'Pre-Shared Key',
        'field.rulesetName': 'Название',
        'field.rulesetUrl': 'URL набора правил (.srs)',
        'field.ruleType': 'Тип',
        'field.ruleValue': 'Значение',

        'ph.name': 'Мой VPN',
        'ph.url': 'https://provider.com/subscribe/...',
        'ph.serverName': 'Мой WireGuard',
        'ph.serverAddr': '1.2.3.4 или домен',
        'ph.serverPort': '51820',
        'ph.privateKey': 'ключ base64',
        'ph.peerPublicKey': 'ключ base64',
        'ph.uuid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'ph.password': 'пароль',
        'ph.tlsSni': 'example.com',
        'ph.wsHost': 'example.com',
        'ph.wsPath': '/path',
        'ph.grpcService': 'service_name',
        'ph.httpHost': 'example.com',
        'ph.httpPath': '/path',
        'ph.httpupgradeHost': 'example.com',
        'ph.hyObfsPassword': 'пароль обфускации',
        'ph.localIpv4': '10.0.0.2/32',
        'ph.localIpv6': 'fd00::2/128',
        'ph.dns': '1.1.1.1, 8.8.8.8',
        'ph.allowedIps': '0.0.0.0/0, ::/0',
        'ph.mtu': '1420',
        'ph.reserved': '0, 0, 0',
        'ph.preSharedKey': 'ключ base64',
        'opt.none': 'Нет',
        'opt.disabled': 'Выключен',
        'opt.enabled': 'Включён',
        'field.importUri': 'Импорт из ссылки',
        'ph.importUri': 'vless://... или vmess://... или ss://...',
        'ph.rulesetName': 'GeoIP-CN',
        'ph.rulesetUrl': 'https://.../.srs',
        'ph.domain': 'example.com',
        'ph.ipCidr': '10.0.0.0/8',

        'msg.invalidUri': 'Не удалось разобрать ссылку',
        'msg.pasteUri': 'Вставьте ссылку или заполните вручную',
        'msg.disconnected': 'Отключено',
        'msg.connected': 'Подключено',
        'msg.deleted': 'Удалено',
        'msg.subAdded': 'VPN добавлен',
        'msg.subEnabled': 'VPN включён',
        'msg.subDisabled': 'VPN отключён',
        'msg.subsUpdated': 'VPN обновлены',
        'msg.updateFailed': 'Ошибка обновления',
        'msg.connFailed': 'Ошибка соединения',
        'msg.nodeEnabled': 'Сервер включён',
        'msg.nodeDisabled': 'Сервер отключён',
        'msg.serverAdded': 'Сервер добавлен',
        'msg.rulesetAdded': 'Набор правил добавлен',
        'msg.ruleAdded': 'Правило добавлено',
        'msg.restarted': 'HomeProxy перезапущен',
        'msg.urlRequired': 'URL обязателен',
        'msg.nameUrlRequired': 'Название и URL обязательны',
        'msg.nameAddrPortRequired': 'Название, адрес и порт обязательны',
        'msg.valueRequired': 'Значение обязательно',
        'msg.error': 'Ошибка: ',

        'confirm.deleteSub': 'Удалить VPN «{name}» и все серверы?',
        'confirm.deleteNode': 'Удалить сервер «{name}»?',
        'confirm.deleteRuleset': 'Удалить набор правил «{name}»?',
        'confirm.deleteRule': 'Удалить «{value}»?',
        'confirm.restart': 'Перезапустить HomeProxy?',

        'btn.updating': 'Обновление...',
        'btn.restarting': 'Перезапуск...'
    }
};
